### ISSUE TITLE
Share the dub package of the binding

### ISSUE THREAD

**Issue by NullDott** [DannyArends/bindbc-gles#1]
Hi, i was looking for some OpenGL ES bindings for D, and i saw you made these ones with BindBC, but i couldn't find the package on the DUB page, i assume there's not a package yet... Could you please release one? It would be really helpful.

**Comment by DannyArends** [comment]
Hey,

Sorry for the late response, I'm on holiday. Thanks for taking an interest in the bindings, I'll submit them to dub once I'm back.

Danny

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: BlueTheBZR ***@***.***>
Sent: Wednesday, April 13, 2022 7:23:19 PM
To: DannyArends/bindbc-gles ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DannyArends/bindbc-gles] Share the dub package of the binding (Issue #1)


Hi, i was looking for some OpenGL ES bindings for D, and i saw you made these ones with BindBC, but i couldn't find the package on the DUB page, i assume there's not a package yet... Could you please release one? It would be really helpful.

**Comment by NullDott** [comment]
Thank you so much!

**Comment by NullDott** [comment]
Hi, it's been a while since i first asked, i just wanna know if the bindings will be available soon. Thanks.

**Comment by DannyArends** [comment]
Hey @BlueTheBZR 

Unfortunately there seem to be issues with the DUB repository, as far as I am aware I should not have an account, but for some reason it won't allow me to create one. I submitted a bug report to the D lang forum, https://forum.dlang.org/post/ewjsqhlfaaftykwobvqc@forum.dlang.org but haven't been able to get into contact with the guy who runs dub yet.

You can use it now, in case you want to but you'll have to add it as a local repo in dub, in the dependencies as follows:

````
  "dependencies": {
    "bindbc-loader": "~>0.3.2",
    "bindbc-sdl": "~>0.21.2",
    "bindbc-gles": {
      "version": "~master",
      "path": "../bindbc-gles"
    }
  }
````

This assumes the bindbc-gles repo one level below the dub.json file for your project.

I hope to get access to dub again soon, so that I can just add it to the repo

**Comment by NullDott** [comment]
Oh, i see... I hope the issue with dub could be solve soon, and thank you so much!!

**Comment by DannyArends** [comment]
Got a mail from the dub developer, the e-mail issue is fixed now.
The package is now available via dub at: https://code.dlang.org/packages/bindbc-gles

Sorry for the wait !
